/** @type {import('stylelint').Config} */
module.exports = {
  "plugins": [
    "stylelint-scss",
  ],
  "extends": [
    "stylelint-config-rational-order",
  ],
  "defaultSeverity": "warning",
  "rules": {
    "scss/dollar-variable-pattern": "[a-z][a-zA-Z]+",
    "block-no-empty": true,
    "no-duplicate-selectors": true,
    "no-empty-source": true,
    "no-unknown-animations": true,
    "no-invalid-double-slash-comments": true,
    "color-no-invalid-hex": true,
    "font-family-name-quotes": "always-where-recommended",
    "font-family-no-duplicate-names": true,
    "font-weight-notation": "numeric",
    "function-calc-no-unspaced-operator": true,
    "function-linear-gradient-no-nonstandard-direction": true,
    "function-url-no-scheme-relative": true,
    "function-url-quotes": "always",
    "number-max-precision": 4,
    "string-no-newline": true,
    "length-zero-no-unit": true,
    "unit-no-unknown": true,
    "value-keyword-case": "lower",
    "custom-property-empty-line-before": "never",
    "shorthand-property-no-redundant-values": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-block-no-redundant-longhand-properties": true,
    "declaration-block-single-line-max-declarations": 1,
    "comment-empty-line-before": "always",
    "comment-no-empty": true,
    "comment-whitespace-inside": "always",
    "no-descending-specificity": null,
    "order/order": [
      "dollar-variables",
      "custom-properties",
      "declarations",
      {
        "type": "at-rule",
        "name": "supports",
      },
      {
        "type": "at-rule",
        "name": "media",
      },
      "rules",
    ],
    "order/properties-order": [
      [
        "position",
        "inset",
        "top",
        "right",
        "bottom",
        "left",
        "z-index",
        "display",
        "flex",
        "flex-basis",
        "flex-direction",
        "flex-flow",
        "flex-grow",
        "flex-shrink",
        "flex-wrap",
        "grid",
        "grid-area",
        "grid-auto-rows",
        "grid-auto-columns",
        "grid-auto-flow",
        "grid-gap",
        "grid-row",
        "grid-row-start",
        "grid-row-end",
        "grid-row-gap",
        "grid-column",
        "grid-column-start",
        "grid-column-end",
        "grid-column-gap",
        "grid-template",
        "grid-template-areas",
        "grid-template-rows",
        "grid-template-columns",
        "gap",
        "align-content",
        "align-items",
        "align-self",
        "justify-content",
        "justify-items",
        "justify-self",
        "order",
        "float",
        "clear",
        "box-sizing",
        "width",
        "min-width",
        "max-width",
        "height",
        "min-height",
        "max-height",
        "margin",
        "margin-top",
        "margin-right",
        "margin-bottom",
        "margin-left",
        "padding",
        "padding-top",
        "padding-right",
        "padding-bottom",
        "padding-left",
        "object-fit",
        "object-position",
        "overflow",
        "overflow-x",
        "overflow-y",
        "color",
        "font",
        "font-weight",
        "font-size",
        "font-family",
        "font-style",
        "font-variant",
        "font-size-adjust",
        "font-stretch",
        "font-effect",
        "font-emphasize",
        "font-emphasize-position",
        "font-emphasize-style",
        "font-smooth",
        "line-height",
        "direction",
        "letter-spacing",
        "white-space",
        "text-align",
        "text-align-last",
        "text-transform",
        "text-decoration",
        "text-emphasis",
        "text-emphasis-color",
        "text-emphasis-style",
        "text-emphasis-position",
        "text-indent",
        "text-justify",
        "text-outline",
        "text-wrap",
        "text-overflow",
        "text-overflow-ellipsis",
        "text-overflow-mode",
        "text-orientation",
        "text-shadow",
        "vertical-align",
        "word-wrap",
        "word-break",
        "word-spacing",
        "overflow-wrap",
        "tab-size",
        "hyphens",
        "unicode-bidi",
        "columns",
        "column-count",
        "column-fill",
        "column-gap",
        "column-rule",
        "column-rule-color",
        "column-rule-style",
        "column-rule-width",
        "column-span",
        "column-width",
        "page-break-after",
        "page-break-before",
        "page-break-inside",
        "src",
        "list-style",
        "list-style-position",
        "list-style-type",
        "list-style-image",
        "table-layout",
        "empty-cells",
        "caption-side",
        "background",
        "background-color",
        "background-image",
        "background-repeat",
        "background-position",
        "background-position-x",
        "background-position-y",
        "background-size",
        "background-clip",
        "background-origin",
        "background-attachment",
        "background-blend-mode",
        "border",
        "border-color",
        "border-style",
        "border-width",
        "border-top",
        "border-top-color",
        "border-top-width",
        "border-top-style",
        "border-right",
        "border-right-color",
        "border-right-width",
        "border-right-style",
        "border-bottom",
        "border-bottom-color",
        "border-bottom-width",
        "border-bottom-style",
        "border-left",
        "border-left-color",
        "border-left-width",
        "border-left-style",
        "border-radius",
        "border-top-left-radius",
        "border-top-right-radius",
        "border-bottom-right-radius",
        "border-bottom-left-radius",
        "border-image",
        "border-image-source",
        "border-image-slice",
        "border-image-width",
        "border-image-outset",
        "border-image-repeat",
        "border-collapse",
        "border-spacing",
        "outline",
        "outline-width",
        "outline-style",
        "outline-color",
        "outline-offset",
        "box-shadow",
        "box-decoration-break",
        "transform",
        "transform-origin",
        "transform-style",
        "backface-visibility",
        "perspective",
        "perspective-origin",
        "visibility",
        "cursor",
        "opacity",
        "filter",
        "isolation",
        "backdrop-filter",
        "mix-blend-mode",
        "transition",
        "transition-delay",
        "transition-timing-function",
        "transition-duration",
        "transition-property",
        "animation",
        "animation-name",
        "animation-duration",
        "animation-play-state",
        "animation-timing-function",
        "animation-delay",
        "animation-iteration-count",
        "animation-direction",
        "animation-fill-mode",
        "appearance",
        "content",
        "clip",
        "clip-path",
        "counter-reset",
        "counter-increment",
        "resize",
        "user-select",
        "nav-index",
        "nav-up",
        "nav-right",
        "nav-down",
        "nav-left",
        "pointer-events",
        "quotes",
        "touch-action",
        "will-change",
        "zoom",
        "fill",
        "fill-rule",
        "clip-rule",
        "stroke",
      ],
      {
        "unspecified": "bottom",
        "severity": "warning",
      },
    ],
  },
}
